#!/bin/bash

# Small Tasks runner script
# -------------------------
# Usage: ./task task_name
# Note: It requires `PKG_NAME` env variable for `build` task in your `package.json`.
#
#    "scripts": {
#        "build": env NODE_ENV=production PKG_NAME=$npm_package_name ./task build
#    }
#

# Packages:
#  Typescript
TSC=node_modules/typescript/bin/tsc
#  Rollup
RUP=node_modules/rollup/bin/rollup
#  Karma
KRM=node_modules/karma/bin/karma
#  TSLint
TSL=node_modules/tslint/bin/tslint

# Files & directories
TSL_FILE=tsconfig.json
DIST_DIR=dist

# Allowed tasks
ALLOWED_TASKS="^(build|test|lint|tsc)$"

# Styles
bold=$(tput bold)
normal=$(tput sgr0)

# Tasks start

function build () {
    clean
    test
    compile
    copy
}

function test () {
    lint
    $KRM start --single-run --reporters spec
}

function lint () {
    $TSL --format stylish --project $TSL_FILE
}

function clean () {
    rm -rf .cache
    rm -rf $DIST_DIR
}

function compile () {
    tsc
    jsc
    cjs
}

function tsc () {
    $TSC --outDir .cache --module es2015
}

function cjs () {
    env MODULE_FORMAT=cjs $RUP -c
}

function jsc () {
    env MODULE_FORMAT=umd $RUP -c
}

function test_watch () {
    env NODE_ENV=debug $KRM start
}

function copy () {
    cp ./index.d.ts $DIST_DIR/
}

# Tasks end


# Check the incoming task
if [[ -z "$1" ]]; then
    echo
    echo "⛔️  No task was provided."
    echo
    exit 1
fi

# Validate if the task is allowed
if [[ $1 =~ $ALLOWED_TASKS ]]; then
    echo
    echo "✅  Running ${bold}$1${normal} task..."
    echo

    # Ok, just let it be!
    $1
else
    echo
    echo "⛔️  Task provided is not available."
    echo
    exit 1
fi
